### ISSUE TITLE
Use tenv instead of tfenv

### ISSUE THREAD

**Issue by kvendingoldo** [phillbaker/dotfiles#3]
Hi. Great repo! I see that you use tfenv here: https://github.com/phillbaker/dotfiles/blob/dbdc0e29bd81b7ff5ae2468e121fa80f0ed9efb7/.brew#L48C3-L48C62

I suggest you to switch to tenv: https://github.com/tofuutils/tenv:
* it is a successor of [tofuenv](https://github.com/tofuutils/tofuenv) and [tfenv](https://github.com/tfutils/tfenv)
* can manage versions of OpenTofu / Terraform / Terragrunt and Atmos
* does not require any dependencies like jq / bash / etc

**Comment by phillbaker** [comment]
Hi @kvendingoldo thanks for opening an issue. I see that you're a contributor to tenv. Honestly, if I updated, I'd probably move to asdf which can also manage terraform. For now I'll close this issue out.
